# Uncomment the next line to define a global platform for your project
# platform :ios, '12.1'

target 'twofold' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for twofold
    pod 'Firebase/AdMob'

  target 'twofoldTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'twofoldUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
